// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package template

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func DeleteForm() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form id=\"markedForDeletion\" hx-swap-oob=\"true\" x-cloak x-data=\"{ idsToDelete: [], deleteHref: &#39;provider&#39; }\" x-show=\"idsToDelete.length &gt; 0\" @change-delete-mark-type=\"deleteHref = $event.detail; idsToDelete = []; callback = true;\" @toggle-mark-for-delete.window=\"if ($event.detail.isChecked &amp;&amp; idsToDelete.indexOf($event.detail.id) === -1) { idsToDelete = [...idsToDelete, $event.detail.id] } else if (!$event.detail.isChecked &amp;&amp; idsToDelete.indexOf($event.detail.id) !== -1) { idsToDelete = idsToDelete.filter(i =&gt; i !== $event.detail.id) } callback = true;\" class=\"absolute itemx-center shadow-lg border px-4 py-2 flex self-center rounded-sm z-5 bottom-4 justify-self-end text-wider bg-blue-400 text-white\" style=\"display: none;\"><span x-text=\"idsToDelete.length\" class=\"self-center\"></span> <span class=\"self-center\">&nbsp;item(s) are selected</span> <span class=\"flex-1\"></span> <input type=\"hidden\" name=\"ids\" :value=\"idsToDelete\"> <button :hx-delete=\"&#39;/partial/&#39; + deleteHref\" hx-params=\"*\" type=\"button\" class=\"bg-red-500 hover:bg-red-600 active:bg-red-700 transition-colors duration-100 cursor-pointer px-4 py-2 ml-4 font-semibold rounded-md\">DELETE\r</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
